// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/r/:slug": {
    params: {
      "slug": string;
    };
  };
  "/r/:slug/items": {
    params: {
      "slug": string;
    };
  };
  "/r/:slug/review": {
    params: {
      "slug": string;
    };
  };
  "/r/:slug/status/:reference": {
    params: {
      "slug": string;
      "reference": string;
    };
  };
  "/admin/login": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/returns": {
    params: {};
  };
  "/admin/returns/:id": {
    params: {
      "id": string;
    };
  };
  "/admin/settings": {
    params: {};
  };
  "/admin/settings/reasons": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/r/:slug" | "/r/:slug/items" | "/r/:slug/review" | "/r/:slug/status/:reference" | "/admin/login" | "/admin" | "/admin/returns" | "/admin/returns/:id" | "/admin/settings" | "/admin/settings/reasons" | "/*";
  };
  "Home.tsx": {
    id: "Home";
    page: "/";
  };
  "portal/PortalLayout.tsx": {
    id: "portal/PortalLayout";
    page: "/r/:slug" | "/r/:slug/items" | "/r/:slug/review" | "/r/:slug/status/:reference";
  };
  "portal/LookupPage.tsx": {
    id: "portal/LookupPage";
    page: "/r/:slug";
  };
  "portal/SelectItemsPage.tsx": {
    id: "portal/SelectItemsPage";
    page: "/r/:slug/items";
  };
  "portal/ReviewPage.tsx": {
    id: "portal/ReviewPage";
    page: "/r/:slug/review";
  };
  "portal/StatusPage.tsx": {
    id: "portal/StatusPage";
    page: "/r/:slug/status/:reference";
  };
  "admin/AuthLayout.tsx": {
    id: "admin/AuthLayout";
    page: "/admin/login" | "/admin" | "/admin/returns" | "/admin/returns/:id" | "/admin/settings" | "/admin/settings/reasons";
  };
  "admin/LoginPage.tsx": {
    id: "admin/LoginPage";
    page: "/admin/login";
  };
  "admin/AdminLayout.tsx": {
    id: "admin/AdminLayout";
    page: "/admin" | "/admin/returns" | "/admin/returns/:id" | "/admin/settings" | "/admin/settings/reasons";
  };
  "admin/DashboardPage.tsx": {
    id: "admin/DashboardPage";
    page: "/admin";
  };
  "admin/ReturnsListPage.tsx": {
    id: "admin/ReturnsListPage";
    page: "/admin/returns";
  };
  "admin/ReturnDetailPage.tsx": {
    id: "admin/ReturnDetailPage";
    page: "/admin/returns/:id";
  };
  "admin/SettingsPage.tsx": {
    id: "admin/SettingsPage";
    page: "/admin/settings";
  };
  "admin/ReasonsPage.tsx": {
    id: "admin/ReasonsPage";
    page: "/admin/settings/reasons";
  };
  "NotFound.tsx": {
    id: "NotFound";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "Home": typeof import("./src/Home.tsx");
  "portal/PortalLayout": typeof import("./src/portal/PortalLayout.tsx");
  "portal/LookupPage": typeof import("./src/portal/LookupPage.tsx");
  "portal/SelectItemsPage": typeof import("./src/portal/SelectItemsPage.tsx");
  "portal/ReviewPage": typeof import("./src/portal/ReviewPage.tsx");
  "portal/StatusPage": typeof import("./src/portal/StatusPage.tsx");
  "admin/AuthLayout": typeof import("./src/admin/AuthLayout.tsx");
  "admin/LoginPage": typeof import("./src/admin/LoginPage.tsx");
  "admin/AdminLayout": typeof import("./src/admin/AdminLayout.tsx");
  "admin/DashboardPage": typeof import("./src/admin/DashboardPage.tsx");
  "admin/ReturnsListPage": typeof import("./src/admin/ReturnsListPage.tsx");
  "admin/ReturnDetailPage": typeof import("./src/admin/ReturnDetailPage.tsx");
  "admin/SettingsPage": typeof import("./src/admin/SettingsPage.tsx");
  "admin/ReasonsPage": typeof import("./src/admin/ReasonsPage.tsx");
  "NotFound": typeof import("./src/NotFound.tsx");
};